org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
geckolib_version=4.4.9

mod_id=frozen_dominion_spells
mod_file_name=Frozen_Dominion_Spells
mod_name=Iron's Spellbooks: Frozen Dominion
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.jastkub.fdspells
mod_authors=Jastkub
mod_description=Eight spells of ice for Iron's Spells 'n Spellbooks, out of the Frozen Dominion: an avalanche, a rain of icicles, a javelin that stands as a pillar, shackles, a heart of frost, a litany of runes, an ice sentinel and a shell of frost.
