package com.jastkub.frozenfortress.entity.boss;

import com.jastkub.frozenfortress.registry.FFEntities;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.syncher.EntityDataAccessor;
import net.minecraft.network.syncher.EntityDataSerializers;
import net.minecraft.network.syncher.SynchedEntityData;
import net.minecraft.util.RandomSource;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.level.Level;
import net.minecraft.world.phys.Vec3;

/**
 * A piece of the king's plate, thrown clear when the armour lets go.
 *
 * <p>WHY THIS EXISTS AT ALL. The phase break spent its shards as particles,
 * and particles cannot do this job however many of them are thrown: a particle
 * is a small camera-facing billboard with a fixed life, so a hundred of them
 * read as dust or sparks - the vocabulary of something being VAPOURISED. What
 * the armour coming off has to say is the opposite, that solid heavy objects
 * have been separated from him and are now loose in the room. That needs
 * things with a size, a tumble and a landing, and the moment they have those
 * they are entities.
 *
 * <p>AND EACH ONE IS A PIECE OF WHAT HE WAS WEARING.
 * They were generic grey boxes; now the kind names one box of his own model - a cell of the breastplate, of the
 * gate, of the pauldron - and ArmourShardRenderer draws exactly that, with its own paint. The table of them is
 * {@link #PIECES}, written by tools/gen_velkhar_armour_pieces.py from velkhar.geo.json.
 *
 * <p>They carry no damage and no collision against the player. The break is a
 * cutscene; being killed by the scenery of one teaches nothing.
 */
public class ArmourShardEntity extends Entity {

    /** How long a piece lives, so the floor is not littered - the last SINK of it spent sinking out of sight. */
    public static final int LIFETIME = 170;
    public static final int SINK = 24;

    /** Which piece this is - see {@link #PIECES} and ArmourShardRenderer. */
    private static final EntityDataAccessor<Integer> KIND =
            SynchedEntityData.defineId(ArmourShardEntity.class, EntityDataSerializers.INT);

    // ================================================================
    // THE PIECES. Each row: the packed kind - bit 26 set; the bone (bits 0-2, ArmourShardRenderer.BONES), the box of
    // it (3-8), the two axes it is cut along (9-10, 11-12), how many cells along each (13-15, 16-18) and which cell
    // this is (19-21, 22-24) - and where its middle sits on him in tenths of his model's sixteenths (the gate's
    // pieces: from the middle of the gate).
    // ================================================================
    // <PIECES> generated by tools/gen_velkhar_armour_pieces.py from velkhar.geo.json - do not edit
    static final int[][] PIECES = {
            {67332096, -100, -152, 44}, // shield
            {71526400, -100, -25, 44}, // shield
            {75720704, -100, 102, 44}, // shield
            {67856384, 0, -152, 44}, // shield
            {72050688, 0, -25, 44}, // shield
            {76244992, 0, 102, 44}, // shield
            {68380672, 100, -152, 44}, // shield
            {72574976, 100, -25, 44}, // shield
            {76769280, 100, 102, 44}, // shield
            {67203080, -104, -236, 44}, // shield
            {67727368, 0, -236, 44}, // shield
            {68251656, 104, -236, 44}, // shield
            {67323920, -57, -122, 25}, // shield
            {71518224, -57, -17, 25}, // shield
            {75712528, -57, 88, 25}, // shield
            {67848208, 57, -122, 25}, // shield
            {72042512, 57, -17, 25}, // shield
            {76236816, 57, 88, 25}, // shield
            {67315872, -128, -150, 17}, // shield
            {71510176, -128, -26, 17}, // shield
            {75704480, -128, 99, 17}, // shield
            {67315880, 128, -150, 17}, // shield
            {71510184, 128, -26, 17}, // shield
            {75704488, 128, 99, 17}, // shield
            {67203248, -97, 146, 19}, // shield
            {67727536, 0, 146, 19}, // shield
            {68251824, 97, 146, 19}, // shield
            {67203256, -97, -193, 19}, // shield
            {67727544, 0, -193, 19}, // shield
            {68251832, 97, -193, 19}, // shield
            {67195664, -148, -18, 18}, // shield
            {67719952, -142, 57, 18}, // shield
            {67258369, -51, 405, -72}, // plate_torso
            {71452673, -51, 475, -72}, // plate_torso
            {67782657, 51, 405, -72}, // plate_torso
            {71976961, 51, 475, -72}, // plate_torso
            {67194889, -52, 370, -73}, // plate_torso
            {67719177, 53, 370, -73}, // plate_torso
            {67194897, -53, 498, -73}, // plate_torso
            {67719185, 53, 498, -73}, // plate_torso
            {67184665, -81, 430, -92}, // plate_torso
            {67184673, 81, 430, -92}, // plate_torso
            {67258409, -49, 402, 66}, // plate_torso
            {71452713, -49, 468, 66}, // plate_torso
            {67782697, 49, 402, 66}, // plate_torso
            {71977001, 49, 468, 66}, // plate_torso
            {67192881, -49, 488, 68}, // plate_torso
            {67717169, 49, 488, 68}, // plate_torso
            {67250233, 92, 404, -73}, // plate_torso
            {71444537, 92, 477, -73}, // plate_torso
            {67250241, -92, 404, -73}, // plate_torso
            {71444545, -92, 477, -73}, // plate_torso
            {67184642, 0, 290, -54}, // plate_skirt
            {67184650, 55, 282, -56}, // plate_skirt
            {67184658, -55, 282, -56}, // plate_skirt
            {67184666, 0, 290, 59}, // plate_skirt
            {67184674, 55, 282, 61}, // plate_skirt
            {67184682, -55, 282, 61}, // plate_skirt
            {67194930, -48, 318, -55}, // plate_skirt
            {67719218, 48, 318, -55}, // plate_skirt
            {67192890, -48, 318, 60}, // plate_skirt
            {67717178, 48, 318, 60}, // plate_skirt
            {67184706, 0, 287, -70}, // plate_skirt
            {67260419, 124, 496, -33}, // plate_pauld_r
            {71454723, 124, 496, 33}, // plate_pauld_r
            {67784707, 193, 519, -33}, // plate_pauld_r
            {71979011, 193, 519, 33}, // plate_pauld_r
            {67260427, 124, 531, -31}, // plate_pauld_r
            {71454731, 124, 531, 31}, // plate_pauld_r
            {67784715, 187, 543, -31}, // plate_pauld_r
            {71979019, 187, 543, 31}, // plate_pauld_r
            {67252243, 149, 560, -28}, // plate_pauld_r
            {71446547, 149, 560, 28}, // plate_pauld_r
            {67260443, 127, 464, -31}, // plate_pauld_r
            {71454747, 127, 464, 31}, // plate_pauld_r
            {67784731, 192, 485, -31}, // plate_pauld_r
            {71979035, 192, 485, 31}, // plate_pauld_r
            {67184675, 151, 501, -71}, // plate_pauld_r
            {67187204, 120, 432, 0}, // plate_arm_r
            {67186700, 120, 461, 0}, // plate_arm_r
            {67187205, -100, 427, 0}, // plate_arm_l
            {67186701, -100, 459, 0}, // plate_arm_l
    };
    // </PIECES>

    /** Tumble, in degrees per tick. Set once and never revisited - on BOTH sides (see {@link #tick}). */
    private float spinYaw;
    private float spinPitch;
    private boolean spun;
    /** Client-side only: how far it has tumbled. Nothing needs this synced. */
    public float rollYaw;
    public float rollPitch;
    public float prevRollYaw;
    public float prevRollPitch;
    /** Client-side only: how far it has settled flat since it landed, 0 to 1. */
    public float settle;
    public float prevSettle;

    public ArmourShardEntity(EntityType<? extends ArmourShardEntity> type, Level level) {
        super(type, level);
    }

    public ArmourShardEntity(Level level, Vec3 from, Vec3 velocity, int kind) {
        this(FFEntities.ARMOUR_SHARD.get(), level);
        setPos(from.x, from.y, from.z);
        setDeltaMovement(velocity);
        this.entityData.set(KIND, kind);
    }

    public int kind() {
        return this.entityData.get(KIND);
    }

    /** True for a kind that names a piece of his model (every one thrown now). */
    public static boolean isPiece(int kind) {
        return (kind & (1 << 26)) != 0;
    }

    @Override
    protected void defineSynchedData(net.minecraft.network.syncher.SynchedEntityData.Builder builder) {
        builder.define(KIND, 0);
    }

    @Override
    public void tick() {
        super.tick();
        this.prevRollYaw = this.rollYaw;
        this.prevRollPitch = this.rollPitch;
        this.prevSettle = this.settle;

        if (this.tickCount > LIFETIME) {
            discard();
            return;
        }
        // THE TUMBLE IS DECIDED ON THE FIRST TICK, ON EACH SIDE. It used to be set in the constructor the server
        // calls - and the client's copy is built from the spawn packet through the other constructor, so on the
        // only side that draws it the spin was zero and every piece sailed through the air dead level. It is seeded
        // from the id, so both sides agree, and tied to how hard it was thrown (the spawn packet carries the
        // velocity): a slab that barely moved should not spin like a coin, and one flung across the room should
        // not sail level.
        if (!this.spun) {
            this.spun = true;
            RandomSource rs = RandomSource.create(getId() * 0x9E3779B97F4A7C15L);
            float force = (float) getDeltaMovement().length();
            this.spinYaw = (rs.nextFloat() - 0.5F) * 44.0F * (0.4F + force);
            this.spinPitch = (rs.nextFloat() - 0.5F) * 38.0F * (0.4F + force);
            this.rollYaw = rs.nextFloat() * 360.0F;
            this.prevRollYaw = this.rollYaw;
        }

        Vec3 v = getDeltaMovement();
        // gravity, and rather more drag than a thrown block gets - these are
        // broad flat plates, and flat things do not keep their speed
        v = new Vec3(v.x * 0.94D, (v.y - 0.055D) * 0.985D, v.z * 0.94D);

        if (this.onGround()) {
            // it skids, it does not bounce: half a ton of plate hitting stone
            // stops, and a bouncing piece of armour reads as plastic
            v = new Vec3(v.x * 0.55D, 0.0D, v.z * 0.55D);
            this.spinYaw *= 0.55F;
            this.spinPitch *= 0.35F;
            // and it falls flat on its broad face (ArmourShardRenderer eases the tumble to the nearest flat)
            this.settle = Math.min(1.0F, this.settle + 0.25F);
        } else {
            this.rollYaw += this.spinYaw;
            this.rollPitch += this.spinPitch;
        }

        setDeltaMovement(v);
        move(net.minecraft.world.entity.MoverType.SELF, getDeltaMovement());
    }

    @Override
    public boolean isPickable() {
        return false;
    }

    @Override
    public boolean shouldRenderAtSqrDistance(double dist) {
        return dist < 4096.0D;
    }

    /** Cosmetic and short-lived; a reload has nothing to restore. */
    @Override
    public boolean shouldBeSaved() {
        return false;
    }

    @Override
    protected void readAdditionalSaveData(CompoundTag tag) {
        this.entityData.set(KIND, tag.getInt("Kind"));
    }

    @Override
    protected void addAdditionalSaveData(CompoundTag tag) {
        tag.putInt("Kind", this.entityData.get(KIND));
    }

    @Override
    public net.minecraft.network.protocol.Packet<net.minecraft.network.protocol.game.ClientGamePacketListener>
            getAddEntityPacket(net.minecraft.server.level.ServerEntity serverEntity) {
        return new net.minecraft.network.protocol.game.ClientboundAddEntityPacket(this, serverEntity);
    }
}
